FlipSide/Models/ErrorViewModel.cs
using System;

namespace FlipSide.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FlipSide/Models/Story.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace FlipSide.Models
{
    public class Story
    {
        public int ID { get; set; }
        [DataType(DataType.Date)]
        public DateTime dateRan { get; set; }
        public string slug { get; set; }
        public string summary { get; set; }
        public string link { get; set; }
        public string byline { get; set; }
        public int lean { get; set; }
        public int is_active { get; set; }
        public string topic { get; set; }
    }
}


//SELECT TOP(1000) [id]
//      ,[dateRan]
//      ,[slug]
//      ,[summary]
//      ,[byline]
//      ,[lean]
//FROM[FlipSide].[dbo].[story] 

FlipSide/Models/Topics.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FlipSide.Models
{
    public class Topics
    {
        public int ID { get; set; }
        public string slug { get; set; }

    }
}

FlipSide/Controllers/HelloWorldController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace MvcMovie.Controllers
{
    public class HelloWorldController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Welcome(string name, int numTimes = 1)
        {
            ViewData["Message"] = "Hello " + name;
            ViewData["NumTimes"] = numTimes;

            return View();
        }
    }
}

FlipSide/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FlipSide.Models;

namespace FlipSide.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FlipSide/Controllers/StoriesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FlipSide.Models;

namespace FlipSide.Controllers
{
    public class StoriesController : Controller
    {
        private readonly FlipSideDataContext _context;

        public StoriesController(FlipSideDataContext context)
        {
            _context = context;
        }

        // GET: Stories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Story.ToListAsync());
        }

        //private IActionResult View(object p)
        //{
        //    throw new NotImplementedException();
        //}

        // GET: Stories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var story = await _context.Story
                .SingleOrDefaultAsync(m => m.ID == id);
            if (story == null)
            {
                return NotFound();
            }

            return View(story);
        }

        // GET: Stories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Stories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,dateRan,slug,summary,byline,link,lean,topic")] Story story)
        {
            if (ModelState.IsValid)
            {
                _context.Add(story);
                await _context.SaveChangesAsync();
                //_context.Add(Topics);
                return RedirectToAction(nameof(Index));
            }
            return View(story);
        }

        // GET: Stories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var story = await _context.Story.SingleOrDefaultAsync(m => m.ID == id);
            if (story == null)
            {
                return NotFound();
            }
            return View(story);
        }

        // POST: Stories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,dateRan,slug,summary,byline,link,lean")] Story story)
        {
            if (id != story.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(story);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StoryExists(story.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(story);
        }

        // GET: Stories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var story = await _context.Story
                .SingleOrDefaultAsync(m => m.ID == id);
            if (story == null)
            {
                return NotFound();
            }

            return View(story);
        }

        // POST: Stories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var story = await _context.Story.SingleOrDefaultAsync(m => m.ID == id);
            _context.Story.Remove(story);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StoryExists(int id)
        {
            return _context.Story.Any(e => e.ID == id);
        }
    }
}

FlipSide/Views/HelloWorld/Index.cshtml
@{
    ViewData["Title"] = "Story List";
}

<h2>My Story List</h2>

<p>Hello from our View Template!</p>

FlipSide/Views/HelloWorld/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<h2>Welcome</h2>

<ul>
    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
    {
        <li>@ViewData["Message"]</li>
    }
</ul>

FlipSide/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

FlipSide/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FlipSide/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

FlipSide/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlipSide</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Stories" asp-action="Index" class="navbar-brand">FlipSide</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - FlipSide</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

FlipSide/Views/Stories/Create.cshtml
@model FlipSide.Models.Story

@{
    ViewData["Title"] = "Create";

}
<script language="javascript">
    var today = new Date().toJSON().slice(0, 10);
    $("#dateRan").value(today);
</script>

<h2>Create</h2>

<h4>Story</h4>
<hr />
<table>
    <tr><td colspan="2" align="center" style="padding:20px">
    <label asp-for="topic" class="control-label"></label>
    <input asp-for="topic" class="form-control" />
</td></tr>
    <tr>
        <td style="vertical-align:top;padding:10px; border:3px solid blue">
            <form id="form1" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="dateRan" class="control-label"></label>
                    <input asp-for="dateRan" class="form-control">
                    <span asp-validation-for="dateRan" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="slug" class="control-label"></label>
                    <input asp-for="slug" class="form-control" />
                    <span asp-validation-for="slug" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="summary" class="control-label"></label>
                    <input asp-for="summary" class="form-control" />
                    <span asp-validation-for="summary" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="byline" class="control-label"></label>
                    <input asp-for="byline" class="form-control" />
                    <span asp-validation-for="byline" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="lean" class="control-label"></label>
                    <input asp-for="lean" class="form-control" value="1" />
                    <span asp-validation-for="lean" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="link" class="control-label"></label>
                    <input asp-for="link" class="form-control" />
                    <span asp-validation-for="link" class="text-danger"></span>
                </div>
            </form>
        </td>
        <td style="vertical-align:top;padding:10px; border:3px solid red">

            <form id="form2" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="dateRan" class="control-label"></label>
                    <input asp-for="dateRan" class="form-control" value=today; />
                    <span asp-validation-for="dateRan" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="slug" class="control-label"></label>
                    <input asp-for="slug" class="form-control" />
                    <span asp-validation-for="slug" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="summary" class="control-label"></label>
                    <input asp-for="summary" class="form-control" />
                    <span asp-validation-for="summary" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="byline" class="control-label"></label>
                    <input asp-for="byline" class="form-control" />
                    <span asp-validation-for="byline" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="lean" class="control-label"></label>
                    <input asp-for="lean" class="form-control" value="2" />
                    <span asp-validation-for="lean" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="link" class="control-label"></label>
                    <input asp-for="link" class="form-control" />
                    <span asp-validation-for="link" class="text-danger"></span>
                </div>
            </form>
        </td>
    </tr>
</table>
<div class="form-group">
    <input type="image" alt="Create" onclick="submitForms()" class="btn btn-default" />
</div>
<script language="javascript">
    var today = new Date().toJSON().slice(0, 10);
    document.getElementsByName("dateRan")[0].value = today;
    document.getElementsByName("dateRan")[1].value = today;

    submitForms = function () {
        document.getElementById("form1").submit();
        document.getElementById("form2").submit();
    }

</script>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FlipSide/Views/Stories/Delete.cshtml
@model MvcMovie.Models.Story

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Story</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.dateRan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dateRan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.slug)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.slug)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.summary)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.summary)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.byline)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.byline)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.lean)
        </dt>
        <dt>
            @Html.DisplayFor(model => model.link)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.lean)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FlipSide/Views/Stories/Details.cshtml
@model MvcMovie.Models.Story

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Story</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.dateRan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dateRan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.slug)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.slug)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.summary)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.summary)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.byline)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.byline)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.lean)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.lean)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.link)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.link)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FlipSide/Views/Stories/Edit.cshtml
@model MvcMovie.Models.Story

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Story</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="dateRan" class="control-label"></label>
                <input asp-for="dateRan" class="form-control" />
                <span asp-validation-for="dateRan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="slug" class="control-label"></label>
                <input asp-for="slug" class="form-control" />
                <span asp-validation-for="slug" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="summary" class="control-label"></label>
                <input asp-for="summary" class="form-control" />
                <span asp-validation-for="summary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="byline" class="control-label"></label>
                <input asp-for="byline" class="form-control" />
                <span asp-validation-for="byline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lean" class="control-label"></label>
                <input asp-for="lean" class="form-control" />
                <span asp-validation-for="lean" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="link" class="control-label"></label>
                <input asp-for="link" class="form-control" />
                <span asp-validation-for="link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FlipSide/Views/Stories/Index.cshtml
@model IEnumerable<FlipSide.Models.Story>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.dateRan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.slug)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.summary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.byline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.lean)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.link)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model)
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.dateRan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.slug)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.summary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.byline)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lean)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.link)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FlipSide/Views/Stories/IndexOld.cshtml
@model IEnumerable<MvcMovie.Models.Story>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.dateRan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.slug)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.summary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.byline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.lean)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.link)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model)
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.dateRan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.slug)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.summary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.byline)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lean)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.link)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>